# default rules
mail_test:
  url: /mail
  param: {module: mail, action: test}

#Solr Search
solr:
  url: /solr/:query
  param: {module: solr, action: search, query: ''}


loi_redirect_article:
  url: /redirect/loi/:loi/:article
  param: {module: loi, action: redirect}

loi_redirect:
  url: /redirect/loi/:loi
  param: {module: loi, action: redirect}

loi_alinea:
  url: /loi/alinea/:id
  param: {module: loi, action: alinea}

loi_alinea_commentaires:
  url: /loi/alinea/:id/commentaires
  param: {module: commentaire, action: showAjax, alinea: 1}

loi_article:
  url: /loi/:loi/article/:article
  param: {module: loi, action: article}

loi_article_id:
  url: /loi/article/:id
  param: {module: loi, action: article}

loi_article_commentaires_json:
  url: /loi/article/:article/commentaires
  param: {module: commentaire, action: json}

loi_section:
  url: /loi/:loi/section/:chapitre/:section
  param: {module: loi, action: section}

loi_chapitre:
  url: /loi/:loi/section/:chapitre
  param: {module: loi, action: section, section: "0"}

loi_rss_commentaires:
  url: /loi/:loi/commentaires/rss
  param: {module: commentaire, action: list, rss: 1}

loi_commentaires:
  url: /loi/:loi/commentaires
  param: {module: commentaire, action: list}

loi:
  url: /loi/:loi
  param: {module: loi, action: loi}

homepage:
  url: /
  param: {module: parlementaire, action: index}
# Les commentaires 
commentaire_post:
  url: /commentaire/:type/:id
  param: {module: commentaire, action: post}
faq_new:
  url: /faq/new
  param: {module: article, action: create, categorie: Faq, hasParent: true, role: "membre", exclude: 1, link: "@faq"}
faq_edit:
  url: /faq/edit/:article_id
  param: {module: article, action: update, categorie: Faq, hasParent: true, role: "membre", exclude: 1}
article_delete:
  url: /article/delete/:article_id
  param: {module: article, action: delete, role: "membre", exclude: 1}
faq:
  url: /faq
  param: {module: article, action: list, categorie: Faq, titre: "Questions fréquemments posées"}
doc_organisme_new:
  url: /organisme/new
  param: {module: article, action: create, categorie: Organisme, hasObject: true, hasTitre: false, isUnique: true, role: "membre", exclude: 1, link: "@list_parlementaires_organisme?slug=%s"}
doc_organisme_edit:
  url: /organisme/edit/:article_id
  param: {module: article, action: edit, categorie: Organisme, hasObject: true, hasTitre: false, isUnique: true, role: "membre", exclude: 1}
rate_id:
  url: /rate/:object_type/:object_id/:rate
  param: {module: rate, action: rateIt}

# Compte Renu
compterendu_list:
  url: /compterendu
  param: {module: article, action: pager, categorie: Seance, titre: "Compte-rendus citoyens"}
compterendu_list:
  url: /compterendu
  param: {module: article, action: pager, categorie: Seance, titre: "Compte-rendus citoyens"}
compterendu_post:
  url: /compterendu/:citoyen/:slug
  param: {module: article, action: show, categorie: Seance}
compterendu_finseance:
  url: /compterendu/new
  param: {module: article, action: findSeance}
compterendu_new:
  url: /compterendu/new/:object_id
  param: {module: article, action: create, categorie: Seance, hasObject: true, displayObject: false, hasTitre: false, isUnique: false, autoObjectTitre: 'Compte-rendu citoyen de la ', link: "@compterendu_post?slug=%s&citoyen=%s", role: "", exclude: 0}
compterendu_edit:
  url: /compterendu/edit/:article_id
  param: {module: article, action: edit, categorie: Seance, hasObject: true, displayObject: false, isUnique: false, role: "", exclude: 0}

depute_id:
  url: /id/:id
  param: {module: parlementaire, action: id}
parlementaire_id:
  url: /parlementaire/id/:id
  param: {module: parlementaire, action: id}
# Liste de tous les parlementaires ou par catégorie
parlementaires_tags:
  url: /deputes/tags
  param: {module: parlementaire, action: tag}
tag_result_parlementaires:
  url: /deputes/tags/:tags
  param: {module: parlementaire, action: tag}
list_parlementaires_search:
  url: /deputes/rechercher/:search
  param: {module: parlementaire, action: list}
list_parlementaires_search_empty:
  url: /deputes/rechercher/
  param: {module: parlementaire, action: list}
list_parlementaires_alpha:
  url: /deputes/:search
  param: {module: parlementaire, action: list}
list_parlementaires:
  url: /deputes
  param: {module: parlementaire, action: list}
list_parlementaires_circo:
  url: /circonscription
  param: {module: circonscription, action: list}
list_parlementaires_departement:
  url: /circonscription/departement/:departement
  param: {module: circonscription, action: show}
list_parlementaires_circo_search:
  url: /circonscription/rechercher/:search
  param: {module: circonscription, action: search}
list_parlementaires_circo_search_empty:
  url: /circonscription/rechercher/
  param: {module: circonscription, action: list}
list_parlementaires_circo_france:
  url: /circonscription/carte
  param: {module: circonscription, action: map}
circo_image_png:
  url: /circonscription/image/:circo/:w/:h
  param: {module: circonscription, action: getCircoimagepng}
redirect_parlementaires_circo:
  url: /circonscription/:code
  param: {module: circonscription, action: redirect}
list_parlementaires_profession:
  url: /profession/:search
  param: {module: parlementaire, action: listProfession}
list_parlementaires_profession_empty:
  url: /profession/
  param: {module: parlementaire, action: listProfession}
list_parlementaires_groupe:
  url: /groupe/:acro
  param: {module: parlementaire, action: listGroupe}
list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

photo_parlementaire:
  url: /depute/photo/:slug
  param: {module: parlementaire, action: photo}
resized_photo_parlementaire:
  url: /depute/photo/:slug/:height
  param: {module: parlementaire, action: photo}
flip_resized_photo_parlementaire:
  url: /depute/photo/:slug/:height/flip
  param: {module: parlementaire, action: photo, flip: 1}

# Fiche parlementaire et affichages de ses travaux
parlementaire_random:
  url: /hasard
  param: {module: parlementaire, action: random}
# Sommaire des textes ou du travail d'un texte par sections et pour un parlementaire donné
sections:
  url: /dossiers/:order
  param: {module: section, action: list}
section_rss_commentaires:
  url: /dossier/:id/commentaires/rss
  param: {module: commentaire, action: list, rss: 1}
section_commentaires:
  url: /dossier/:id/commentaires
  param: {module: commentaire, action: list}
section:
  url: /dossier/:id
  param: {module: section, action: show}
intervention:
  url: /intervention/:id
  param: {module: intervention, action: show}
intervention_commentaires:
  url: /intervention/:id/commentaires
  param: {module: commentaire, action: showAjax, intervention: 1, limit: 4}
interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}
presents_seance:
  url: /seance/:seance/presents
  param: {module: presence, action: seance}
seance_commentaires_json:
  url: /seance/:seance/commentaires
  param: {module: commentaire, action: json}
amendement_id:
  url: /amendement/:id
  param: {module: amendement, action: redirect}

amendement:
  url: /amendement/:loi/:numero
  param: {module: amendement, action: show}

find_amendements_by_loi_and_numero:
  url: /amendements/:loi/:numero
  param: {module: amendement, action: find}

# Recherche lexicale d'interventions ou d'amendements
search:
  url: /rechercher
  param: {module: search, action: index}
search_interventions_mots_rss:
  url: /rechercher/interventions/:search/rss
  param: {module: intervention, action: search, rss: 1}
search_interventions_mots:
  url: /rechercher/interventions/:search
  param: {module: intervention, action: search}
search_interventions:
  url: /rechercher/interventions/
  param: {module: intervention, action: search}
search_amendements_mots_rss:
  url: /rechercher/amendements/:search/rss
  param: {module: amendement, action: search, rss: 1}
search_amendements_mots:
  url: /rechercher/amendements/:search
  param: {module: amendement, action: search}
search_amendements:
  url: /rechercher/amendements/
  param: {module: amendement, action: search}
search_questions_ecrites_mots_rss:
  url: /rechercher/questions/:search/rss
  param: {module: questions, action: search, rss: 1}
search_questions_ecrites_mots:
  url: /rechercher/questions/:search
  param: {module: questions, action: search}
search_questions_ecrites:
  url: /rechercher/questions/
  param: {module: questions, action: search}


# Tags d'une intervention, d'une section ou d'un parlementaire, d'une section ou  ou lors d'une séance
tag_interventions:
  url: /tag/:tags
  param: {module: intervention, action: tag}
tag_section_interventions:
  url: /dossier/:section/tag/:tags
  param: {module: intervention, action: tag}
tag_parlementaire_interventions:
  url: /parlementaire/:parlementaire/tag/:tags
  param: {module: intervention, action: tag}

# Top des députés par interventions, présences ou amendements
top_organisme_global_sorted:
  url: /syntheseo/:organisme/tri/:sort
  param: {module: parlementaire, action: top}
top_organisme_global: 
  url: /syntheseo/:organisme
  param: {module: parlementaire, action: top}
top_global_sorted: 
  url: /synthesetri/:sort
  param: {module: parlementaire, action: top}
top_global: 
  url: /synthese
  param: {module: parlementaire, action: top}
api_synthese:
  url: /synthese/:date/:type
  param: {module: api, action: top}

# Affichage d'une question
question_numero:
  url: /question/QE/:numero
  param: {module: questions, action: show}
question:
  url: /question/id/:id
  param: {module: questions, action: redirect}
question_id:
  url: /question/:id
  param: {module: questions, action: redirect}

# Captcha
captcha_image:
  url: /captcha_image
  param: {module: captcha, action: getcaptcha}
captcha_sonore:
  url: /captcha_sonore
  param: {module: captcha, action: getcaptchasonore}

# Authentification
signin:
  url: /login
  param: { module: citoyen, action: signin }
signout:
  url: /logout
  param: { module: citoyen, action: signout }
identification_ajax:
  url: /ajax/identification
  param: {module: citoyen, action: connected}

# Reset password:
reset_mdp:
  url: /reset_password
  param: {module: citoyen, action: resetmotdepasse}
reset_mdp_2:
  url: /reset_password/:slug/:activation_id
  param: {module: citoyen, action: resetmotdepasse}

# Gestion des utilisateurs
inscription:
  url: /citoyens/inscription
  param: {module: citoyen, action: new}
activation_citoyen:
  url: /activation/:slug/:activation_id
  param: {module: citoyen, action: activation}
list_citoyens:
  url: /citoyens
  param: {module: citoyen, action: index}
photo_citoyen:
  url: /citoyen/photo/:slug
  param: {module: citoyen, action: photo}
citoyen:
  url: /citoyen/:slug
  param: {module: citoyen, action: show}
edit_citoyen:
  url: /profil/edition
  param: {module: citoyen, action: edit}
editpassword_citoyen:
  url: /profil/edition/password
  param: {module: citoyen, action: editpassword}
upload_avatar:
  url: /profil/edition/upload
  param: {module: citoyen, action: uploadavatar}
add_circo_citoyen:
  url: /profil/edition/circo/:nom_circo/:num_circo
  param: {module: citoyen, action: addcirco}
delete_citoyen:
  url: /profil/suppression/:token
  param: {module: citoyen, action: delete}

# Commentaires
commentaires:
  url: /commentaires
  param: {module: commentaire, action: list}
commentaires_rss:
  url: /commentaires/rss
  param: {module: commentaire, action: list, rss: 1}

parlementaire:
  url: /:slug
  param: {module: parlementaire, action: show}
parlementaire_rss:
  url: /:slug/rss
  param: {module: parlementaire, action: rss, Intervention: 1, QuestionEcrite: 1, Amendement: 1}
parlementaire_interventions:
  url: /:slug/interventions/:type
  param: {module: intervention, action: parlementaire}
parlementaire_interventions_organisme:
  url: /:slug/organisme/:orga/interventions/
  param: {module: intervention, action: parlementaireOrganisme}
parlementaire_tags:
  url: /:slug/tags
  param: {module: tag, action: parlementaire}
parlementaire_all_tags:
  url: /:slug/tags/all
  param: {module: tag, action: parlementaire, all: 1}
parlementaire_session_tags:
  url: /:slug/tags/:session
  param: {module: tag, action: parlementaire}
parlementaire_rss_commentaires:
  url: /:slug/commentaires/rss
  param: {module: commentaire, action: list, rss: 1}
parlementaire_commentaires:
  url: /:slug/commentaires
  param: {module: commentaire, action: list}
parlementaire_textes:
  url: /:slug/dossiers
  param: {module: section, action: parlementaire}
parlementaire_texte_amendements:
  url: /:slug/dossier/:id/amendements
  param: {module: amendement, action: parlementaireSection}
parlementaire_texte:
  url: /:slug/dossier/:id
  param: {module: section, action: parlementaireSection}
parlementaire_amendements:
  url: /:slug/amendements
  param: {module: amendement, action: parlementaire}
parlementaire_amendements_rss:
  url: /:slug/amendements/rss
  param: {module: parlementaire, action: rss, Amendement: 1}
parlementaire_presences_type:
  url: /:slug/presences/:type
  param: {module: presence, action: parlementaire}
parlementaire_presences:
  url: /:slug/presences
  param: {module: presence, action: parlementaire}
parlementaire_plot:
  url: /:slug/graphes/:time
  param: {module: parlementaire, action: plot}
preuve_presence_seance:
  url: /:slug/seance/:seance
  param: {module: presence, action: preuve}
parlementaire_questions:
  url: /:slug/questions
  param: {module: questions, action: parlementaire}
parlementaire_questions_rss:
  url: /:slug/questions/rss
  param: {module: parlementaire, action: rss, QuestionEcrite: 1}

