# default rules
parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}

list_parlementaires_circo:
  url: /circo/:nom_circo
  param: {module: parlementaire, action: listCirco}

list_parlementaires_profession:
  url: /parlementaire/profession/:profession
  param: {module: parlementaire, action: listProfession}

list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

search_parlementaire:
  url: /parlementaire
  param: {module: parlementaire, action: list}

interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}

parlementaire_presences:
  url: /presence/:slug
  param: {module: presence, action: parlementaire}

presents_seance:
  url: /presence/:seance
  param: {module: presence, action: seance}

preuve_presence_seance:
  url: /preuve/:slug/:seance
  param: {module: presence, action: preuve}

homepage:
  url:   /
  param: { module: parlementaire, action: list }

default:
  url:   /:module/:action/*
