# default rules
mail_test:
  url: /mail
  param: {module: mail, action: test}

homepage:
  url: /
  param: {module: parlementaire, action: index}
# Les commentaires 
commentaire_post:
  url: /commentaire/:type/:id
  param: {module: commentaire, action: post}
faq_new:
  url: /faq/new
  param: {module: article, action: create, categorie: Faq, hasParent: true, role: "membre", exclude: 1, link: "@faq"}
faq_edit:
  url: /faq/edit/:article_id
  param: {module: article, action: update, categorie: Faq, hasParent: true, role: "membre", exclude: 1}
article_delete:
  url: /article/delete/:article_id
  param: {module: article, action: delete, role: "membre", exclude: 1}
faq:
  url: /faq
  param: {module: article, action: list, categorie: Faq, titre: "Questions fréquemments posées"}
doc_organisme_new:
  url: /organisme/new
  param: {module: article, action: create, categorie: Organisme, hasObject: true, hasTitre: false, isUnique: true, role: "membre", exclude: 1, link: "@list_parlementaires_organisme?slug=%s"}
doc_organisme_edit:
  url: /organisme/edit/:article_id
  param: {module: article, action: edit, categorie: Organisme, hasObject: true, hasTitre: false, isUnique: true, role: "membre", exclude: 1}
rate_id:
  url: /rate/:object_type/:object_id/:rate
  param: {module: rate, action: rateIt}

# Compte Renu
compterendu_list:
  url: /compterendu
  param: {module: article, action: pager, categorie: Seance, titre: "Compte-rendus citoyens"}
compterendu_list:
  url: /compterendu
  param: {module: article, action: pager, categorie: Seance, titre: "Compte-rendus citoyens"}
compterendu_post:
  url: /compterendu/:citoyen/:slug
  param: {module: article, action: show, categorie: Seance}
compterendu_finseance:
  url: /compterendu/new
  param: {module: article, action: findSeance}
compterendu_new:
  url: /compterendu/new/:object_id
  param: {module: article, action: create, categorie: Seance, hasObject: true, displayObject: false, hasTitre: false, isUnique: false, autoObjectTitre: 'Compte-rendu citoyen de la ', link: "@compterendu_post?slug=%s&citoyen=%s", role: "", exclude: 0}
compterendu_edit:
  url: /compterendu/edit/:article_id
  param: {module: article, action: edit, categorie: Seance, hasObject: true, displayObject: false, isUnique: false, role: "", exclude: 0}

# Liste de tous les parlementaires ou par catégorie
list_parlementaires:
  url: /deputes
  param: {module: parlementaire, action: list}
list_parlementaires_circo:
  url: /circonscription
  param: {module: parlementaire, action: listCirco}
list_parlementaires_profession:
  url: /profession
  param: {module: parlementaire, action: listProfession}
list_parlementaires_groupe:
  url: /groupe/:acro
  param: {module: parlementaire, action: listGroupe}
list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

parlementaires_tags:
  url: /deputes/tags
  param: {module: parlementaire, action: tag}
tag_result_parlementaires:
  url: /deputes/tags/:tags
  param: {module: parlementaire, action: tag}
photo_parlementaire:
  url: /depute/photo/:slug
  param: {module: parlementaire, action: photo}
resized_photo_parlementaire:
  url: /depute/photo/:slug/:height
  param: {module: parlementaire, action: photo}

# Fiche parlementaire et affichages de ses travaux
parlementaire_random:
  url: /depute_du_jour
  param: {module: parlementaire, action: random}
# Sommaire des textes ou du travail d'un texte par sections et pour un parlementaire donné
sections:
  url: /dossiers/:order
  param: {module: section, action: list}
section:
  url: /dossier/:id
  param: {module: section, action: show}
intervention:
  url: /intervention/:id
  param: {module: intervention, action: show}
interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}
presents_seance:
  url: /seance/:seance/presents
  param: {module: presence, action: seance}
amendement:
  url: /amendement/:id
  param: {module: amendement, action: show}
find_amendements_by_loi_and_numero:
  url: /amendements/:loi/:numero
  param: {module: amendement, action: find}

# Recherche lexicale d'interventions ou d'amendements
search:
  url: /rechercher
  param: {module: search, action: index}
search_interventions:
  url: /rechercher/interventions
  param: {module: intervention, action: search}
search_interventions_mots:
  url: /rechercher/interventions/:search
  param: {module: intervention, action: search}
search_amendements:
  url: /rechercher/amendements
  param: {module: amendement, action: search}
search_amendements_mots:
  url: /rechercher/amendements/:search
  param: {module: amendement, action: search}

# Tags d'une intervention, d'une section ou d'un parlementaire, d'une section ou  ou lors d'une séance
tag_interventions:
  url: /tag/:tags
  param: {module: intervention, action: tag}
tag_section_interventions:
  url: /dossier/:section/tag/:tags
  param: {module: intervention, action: tag}
tag_parlementaire_interventions:
  url: /parlementaire/:parlementaire/tag/:tags
  param: {module: intervention, action: tag}

# Top des députés par interventions, présences ou amendements
top_organisme_global_sorted:
  url: /synthese/:organisme/tri/:sort
  param: {module: parlementaire, action: top}
top_organisme_global: 
  url: /synthese/:organisme
  param: {module: parlementaire, action: top}
top_global_sorted: 
  url: /synthese/tri/:sort
  param: {module: parlementaire, action: top}
top_global: 
  url: /synthese
  param: {module: parlementaire, action: top}

# Affichage d'une question
question:
  url: /question/:id
  param: {module: questions, action: show}

# Authentification
signin:
  url:   /login
  param: { module: citoyen, action: signin }
signout:
  url:   /logout
  param: { module: citoyen, action: signout }

# password:
  # url:   /request_password
  # param: { module: citoyen, action: password }

# Gestion des utilisateurs
inscription:
  url: /citoyens/inscription
  param: {module: citoyen, action: new}
activation_citoyen:
  url: /activation/:slug/:activation_id
  param: {module: citoyen, action: activation}
list_citoyens:
  url: /citoyens
  param: {module: citoyen, action: index}
photo_citoyen:
  url: /citoyen/photo/:slug
  param: {module: citoyen, action: photo}
citoyen:
  url: /citoyen/:slug
  param: {module: citoyen, action: show}
edit_citoyen:
  url: /profil/edition
  param: {module: citoyen, action: edit}
upload_avatar:
  url: /profil/edition/upload
  param: {module: citoyen, action: uploadavatar}
add_circo_citoyen:
  url: /profil/edition/circo/:nom_circo/:num_circo
  param: {module: citoyen, action: addcirco}
delete_citoyen:
  url: /profil/suppression
  param: {module: citoyen, action: delete}


# renvoi_mail_activation_citoyen:
  # url: /citoyens/activation/renvoi/:user_id
  # param: {module: citoyen, action: renvoimailactivation}

# Add include user's module to get same circonscription?


parlementaire:
  url: /:slug
  param: {module: parlementaire, action: show}
parlementaire_rss:
  url: /:slug/rss
  param: {module: parlementaire, action: rss, Intervention: 1, QuestionEcrite: 1, Amendement: 1}
parlementaire_interventions:
  url: /:slug/interventions/:type
  param: {module: intervention, action: parlementaire}
parlementaire_interventions_organisme:
  url: /:slug/organisme/:orga/interventions/
  param: {module: intervention, action: parlementaireOrganisme}
parlementaire_tags:
  url: /:slug/tags
  param: {module: tag, action: parlementaire}
parlementaire_all_tags:
  url: /:slug/tags/all
  param: {module: tag, action: parlementaire, all: 1}
parlementaire_session_tags:
  url: /:slug/tags/:session
  param: {module: tag, action: parlementaire}
parlementaire_rss_commentaires:
  url: /:slug/commentaires/rss
  param: {module: commentaire, action: rss, parlementaire: 1}
parlementaire_commentaires:
  url: /:slug/commentaires
  param: {module: commentaire, action: parlementaire}
parlementaire_textes:
  url: /:slug/dossiers
  param: {module: section, action: parlementaire}
parlementaire_texte_amendements:
  url: /:slug/dossier/:id/amendements
  param: {module: amendement, action: parlementaireSection}
parlementaire_texte:
  url: /:slug/dossier/:id
  param: {module: section, action: parlementaireSection}
parlementaire_amendements:
  url: /:slug/amendements
  param: {module: amendement, action: parlementaire}
parlementaire_presences:
  url: /:slug/presences
  param: {module: presence, action: parlementaire}
parlementaire_plot:
  url: /:slug/graphes/:time
  param: {module: parlementaire, action: plot}
preuve_presence_seance:
  url: /:slug/seance/:seance
  param: {module: presence, action: preuve}
parlementaire_questions:
  url: /:slug/questions
  param: {module: questions, action: parlementaire}
