# default rules
parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}

list_parlementaires_circo:
  url: /parlementaire/circo/:nom_circo
  param: {module: parlementaire, action: listCirco}

list_parlementaires_profession:
  url: /parlementaire/profession/:profession
  param: {module: parlementaire, action: listProfession}

list_parlementaires_organisme:
  url: /parlementaire/organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

search_parlementaire:
  url: /parlementaire
  param: {module: parlementaire, action: list}

homepage:
  url:   /
  param: { module: parlementaire, action: list }

default:
  url:   /:module/:action/*
