# default rules
parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}

search_parlementaire:
  url: /parlementaire
  param: {module: parlementaire, action list}

homepage:
  url:   /
  param: { module: parlementaire, action: list }

default:
  url:   /:module/:action/*
