# default rules
homepage:
  url: /
  param: {module: parlementaire, action: index}
# Les commentaires 
commentaire_post:
  url: /commentaire/:type/:id
  param: {module: commentaire, action: post}


# Liste de tous les parlementaires ou par catégorie
list_parlementaires:
  url: /parlementaire
  param: {module: parlementaire, action: list}
list_parlementaires_circo:
  url: /circonscription
  param: {module: parlementaire, action: listCirco}
list_parlementaires_profession:
  url: /profession
  param: {module: parlementaire, action: listProfession}
list_parlementaires_groupe:
  url: /groupe/:acro
  param: {module: parlementaire, action: listGroupe}
list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

parlementaire_tags:
  url: /parlementaire/tag
  param: {module: parlementaire, action: tag}
tag_result_parlementaires:
  url: /parlementaire/tag/:tags
  param: {module: parlementaire, action: tag}
photo_parlementaire:
  url: /parlementaire/photo/:slug
  param: {module: parlementaire, action: photo}
resized_photo_parlementaire:
  url: /parlementaire/photo/:slug/:height
  param: {module: parlementaire, action: photo}

# Fiche parlementaire et affichages de ses travaux
parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}
parlementaire_interventions:
  url: /parlementaire/:slug/interventions
  param: {module: intervention, action: parlementaire}
parlementaire_commentaires:
  url: /parlementaire/:slug/commentaires
  param: {module: commentaire, action: parlementaire}
parlementaire_textes:
  url: /parlementaire/:slug/textes
  param: {module: section, action: parlementaire}
parlementaire_texte:
  url: /parlementaire/:slug/texte/:id
  param: {module: section, action: parlementaireSection}
parlementaire_amendements:
  url: /parlementaire/:slug/amendements
  param: {module: amendement, action: parlementaire}
parlementaire_presences:
  url: /parlementaire/:slug/presence
  param: {module: presence, action: parlementaire}
plot_parlementaire_presences:
  url: /parlementaire/:slug/presence/plot
  param: {module: parlementaire, action: plotPresences}
preuve_presence_seance:
  url: /parlementaire/:slug/presence/:seance
  param: {module: presence, action: preuve}
parlementaire_questions:
  url: /parlementaire/:slug/questions
  param: {module: questions, action: parlementaire}

# Sommaire des textes ou du travail d'un texte par sections et pour un parlementaire donné
sections:
  url: /section
  param: {module: section, action: list}
section:
  url: /section/:id
  param: {module: section, action: show}
intervention:
  url: /intervention/:id
  param: {module: intervention, action: show}
interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}
presents_seance:
  url: /seance/:seance/presents
  param: {module: presence, action: seance}
amendement:
  url: /amendement/:id
  param: {module: amendement, action: show}
find_amendements_by_loi_and_numero:
  url: /amendements/:loi/:numero
  param: {module: amendement, action: find}

# Recherche lexicale d'interventions ou d'amendements
search:
  url: /rechercher
  param: {module: search, action: index}
search_interventions:
  url: /rechercher/intervention
  param: {module: intervention, action: search}
search_interventions_mots:
  url: /rechercher/intervention/:search
  param: {module: intervention, action: search}
search_amendements:
  url: /rechercher/amendement
  param: {module: amendement, action: search}
search_amendements_mots:
  url: /rechercher/amendement/:search
  param: {module: amendement, action: search}

# Tags d'une intervention, d'une section ou d'un parlementaire, d'une section ou  ou lors d'une séance
tag_interventions:
  url: /tag/:tags
  param: {module: intervention, action: tag}
tag_section_interventions:
  url: /section/:section/tag/:tags
  param: {module: intervention, action: tag}
tag_parlementaire_interventions:
  url: /parlementaire/:parlementaire/tag/:tags
  param: {module: intervention, action: tag}

# Top des députés par interventions, présences ou amendements
top_interventions:
  url: /top/intervention
  param: {module: intervention, action: top}
top_presences:
  url: /top/presence
  param: {module: presence, action: top}
top_amendements:
  url: /top/amendement
  param: {module: amendement, action: top}

# Affichage d'une question
question:
  url: /question/:id
  param: {module: questions, action: show}

# SfGuard
# sf_guard_signin:
  # url:   /login
  # param: { module: sfGuardAuth, action: signin }

# sf_guard_signout:
  # url:   /logout
  # param: { module: sfGuardAuth, action: signout }

# sf_guard_password:
  # url:   /request_password
  # param: { module: sfGuardAuth, action: password }

# Gestion des utilisateurs
inscription:
  url: /citoyens/inscription
  param: {module: citoyen, action: new}

list_citoyens:
  url: /citoyens
  param: {module: citoyen, action: index}

citoyen:
  url: /citoyen/:slug
  param: {module: citoyen, action: show}

edit_citoyen:
  url: /profil/edition
  param: {module: citoyen, action: edit}

add_circo_citoyen:
  url: /profil/circo/:nom_circo/:num_circo
  param: {module: citoyen, action: circo}

delete_citoyen:
  url: /profil/suppression
  param: {module: citoyen, action: delete}

activation_citoyen:
  url: /citoyens/activation/:activation_id
  param: {module: citoyen, action: activation}
# Add include user's module to get same circonscription?
