# default rules
parlementaire:
  url: /parlementaire/:permalink
  param: {module: parlementaire, action: show}

homepage:
  url:   /
  param: { module: parlementaire, action: list }

default:
  url:   /:module/:action/*
