# default rules
homepage:
  url: /
  param: {module: parlementaire, action: index}

# Liste de tous les parlementaires ou par catégorie
list_parlementaires:
  url: /parlementaire
  param: {module: parlementaire, action: list}
list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}
list_parlementaires_circo:
  url: /circonscription/:nom_circo
  param: {module: parlementaire, action: listCirco}
list_parlementaires_profession:
  url: /profession/:profession
  param: {module: parlementaire, action: listProfession}

# Fiche parlementaire et affichages de ses travaux
parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}
parlementaire_interventions:
  url: /parlementaire/:slug/interventions
  param: {module: intervention, action: parlementaire}
parlementaire_textes:
  url: /parlementaire/:slug/textes
  param: {module: section, action: parlementaire}
parlementaire_texte:
  url: /parlementaire/:slug/texte/:id
  param: {module: section, action: parlementaireSection}
parlementaire_amendements:
  url: /parlementaire/:slug/amendements
  param: {module: amendement, action: parlementaire}
parlementaire_presences:
  url: /parlementaire/:slug/presence
  param: {module: presence, action: parlementaire}
preuve_presence_seance:
  url: /parlementaire/:slug/presence/:seance
  param: {module: presence, action: preuve}

# Sommaire des textes ou du travail d'un texte par sections et pour un parlementaire donné
sections:
  url: /section
  param: {module: section, action: list}
section:
  url: /section/:id
  param: {module: section, action: show}
intervention:
  url: /intervention/:id
  param: {module: intervention, action: show}
interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}
presents_seance:
  url: /seance/:seance/presents
  param: {module: presence, action: seance}
amendement:
  url: /amendement/:id
  param: {module: amendement, action: show}
find_amendements_by_loi_and_numero:
  url: /amendements/:loi/:numero
  param: {module: amendement, action: find}

# Recherche lexicale d'interventions ou d'amendements
search:
  url: /rechercher
  param: {module: search, action: index}
search_interventions:
  url: /rechercher/intervention
  param: {module: intervention, action: search}
search_interventions_mots:
  url: /rechercher/intervention/:search
  param: {module: intervention, action: search}
search_amendements:
  url: /rechercher/amendement
  param: {module: amendement, action: search}
search_amendements_mots:
  url: /rechercher/amendement/:search
  param: {module: amendement, action: search}

# Tags d'une intervention, d'une section ou d'un parlementaire, d'une section ou  ou lors d'une séance
tag_interventions:
  url: /tag/:tags
  param: {module: intervention, action: tag}
tag_section_interventions:
  url: /section/:section/tag/:tags
  param: {module: intervention, action: tag}
tag_parlementaire_interventions:
  url: /parlementaire/:parlementaire/tag/:tags
  param: {module: intervention, action: tag}
parlementaire_tags:
  url: /parlementaire/tag
  param: {module: parlementaire, action: tag}
tag_result_parlementaires:
  url: /parlementaire/tag/:tags
  param: {module: parlementaire, action: tag}

# Top des députés par interventions, présences ou amendements
top_interventions:
  url: /top/intervention
  param: {module: intervention, action: top}
top_presences:
  url: /top/presence
  param: {module: presence, action: top}
top_amendements:
  url: /top/amendement
  param: {module: amendement, action: top}

# Gestion des utilisateurs
list_utilisateurs:
  url: /citoyens
  param: {module: utilisateur, action: index}
utilisateur:
  url: /citoyen/:slug
  param: {module: utilisateur, action: show}
edit_utilisateur:
  url: /citoyen/:slug/edition
  param: {module: utilisateur, action: edit}
update_utilisateur:
  url: /citoyen/:slug/edition
  param: {module: utilisateur, action: update}
delete_utilisateur:
  url: /citoyen/:slug/edition
  param: {module: utilisateur, action: delete}
new_utilisateur:
  url: /citoyens/inscription
  param: {module: utilisateur, action: new}
create_utilisateur:
  url: /citoyens/inscription
  param: {module: utilisateur, action: create}
# Add include user's module to get same circonscription?
