# default rules
homepage:
  url: /
  param: {module: parlementaire, action: index}

list_parlementaires:
  url: /parlementaire
  param: {module: parlementaire, action: list}

parlementaire_texte:
  url: /parlementaire/:slug/textes/:id
  param: {module: section, action: parlementaireSection}

parlementaire_textes:
  url: /parlementaire/:slug/textes
  param: {module: section, action: parlementaire}

tag_section_interventions:
  url: /section/:section/tag/:tags
  param: {module: intervention, action: tag}


search_interventions:
  url: /rechercher
  param: {module: intervention, action: search}

search_interventions_mots:
  url: /rechercher/:search
  param: {module: intervention, action: search}

section:
  url: /section/:id
  param: {module: section, action: show}

sections:
  url: /section
  param: {module: section, action: list}

tag_parlementaire_interventions:
  url: /parlementaire/:parlementaire/tag/:tags
  param: {module: intervention, action: tag}

parlementaire:
  url: /parlementaire/:slug
  param: {module: parlementaire, action: show}

list_parlementaires_organisme:
  url: /organisme/:slug
  param: {module: parlementaire, action: listOrganisme}

list_parlementaires_circo:
  url: /circo/:nom_circo
  param: {module: parlementaire, action: listCirco}
# Add include user's module to get same circonscription?

list_parlementaires_profession:
  url: /profession/:profession
  param: {module: parlementaire, action: listProfession}
# Add include user's module to get same job

tag_interventions:
  url: /tag/:tags
  param: {module: intervention, action: tag}

parlementaire_interventions:
  url: /intervention/:slug
  param: {module: intervention, action: parlementaire}

interventions_seance:
  url: /seance/:seance
  param: {module: intervention, action: seance}

parlementaire_presences:
  url: /presence/:slug
  param: {module: presence, action: parlementaire}

plot_parlementaire_presences:
  url: /presence/plot/:slug
  param: {module: presence, action: plotParlementaire}

presents_seance:
  url: /presence/:seance
  param: {module: presence, action: seance}

preuve_presence_seance:
  url: /presence/:slug/:seance
  param: {module: presence, action: preuve}

top_interventions:
  url: /top/intervention
  param: {module: intervention, action: top}

intervention:
  url: /intervention/id/:id
  param: {module: intervention, action: show}

top_presences:
  url: /top/presence
  param: {module: presence, action: top}
