default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    #robots:       index, follow

  stylesheets:    []

  javascripts:    [jquery-1.3.2.min.js]

  has_layout:     true
  layout:         layout
