organisme:
  class: sfDoctrineRouteCollection
  options:
    model:                Organisme
    module:               organisme
    prefix_path:          organisme
    column:               id
    with_wildcard_routes: true

parlementaire:
  class: sfDoctrineRouteCollection
  options:
    model:                Parlementaire
    module:               parlementaire
    prefix_path:          parlementaire
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
