autoload:
  # vendor
  vendor:
    name:           project
    path:           %SF_LIB_DIR%/vendor
    recursive:      true
    exclude:        [symfony, symfony-externals-1.4.6, symfony-externals-1.4]
