options:
    type: MyISAM

Personnalite:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: string(255)
    nom_de_famille: string(255)
    sexe: 
      type: enum
      values: ['H', 'F']

Parlementaire:
  columns:     
    nom_circo: string(255)
    num_circo: integer
    site_web: string(255)
    debut_mandat: date
    place_hemicycle:	integer
    url_an:	string(255)
    profession:	string(255)
    id_an:
      type:	integer
      unique:	true
    type:
      type:	enum
      values:	['depute', 'senateur']
    groupe_acronyme: string(8)
  inheritance:
    extends: Personnalite
    type: concrete
  relations:
    Organismes:
      class: Organisme
      refClass: ParlementaireOrganisme
      foreignAlias: Parlementaires
  indexes:
    uniq_url:
      fields: [url_an]
      type: unique
Organisme:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: 
      type: string(255)
      unique: true
    type:
      type: enum
      values: ['parlementaire', 'groupe', 'extra']

ParlementaireOrganisme:
  columns:
    fonction: string(512)
    importance: integer
    debut_fonction: date
    organisme_id:
      type: integer
      primary: true
    parlementaire_id:
      type: integer
      primary: true
  relations:
    Parlementaire:
      foreignAlias: ParlementaireOrganismes
    Organisme:
      foreignAlias: ParlementaireOrganismes

Seance:
  actAs:
    Timestampable:
  columns:
    date: date
    numero_semaine: integer
    annee: integer
    type:
      type: enum
      values: ['commission', 'hemicycle']
    moment: string(30)
    organisme_id: integer
    tagged: boolean
    session: string(10)
  relations:
    Organisme:
      foreignAlias: Seances
  indexes:
    uniq_index:
      fields: [organisme_id, date, moment]
      type: unique
    index_session:
      fields: [session]
    index_semaine:
      fields: [annee, numero_semaine]
    index_annee:
      fields: [annee]

Presence:
  actAs:
    Timestampable:
  columns:
    parlementaire_id: integer
    seance_id: integer
    nb_preuves: integer
    date: date
  relations:
    Parlementaire:
      foreignAlias: Presences
    Seance:
      foreignAlias: Presences

PreuvePresence:
  actAs:
    Timestampable:
  columns:
    presence_id: integer
    type:
      type: enum
      values: ['jo', 'intervention']
    source: string(200)
  relations:
    Presence:
      foreignAlias: Preuves

Section:
  actAs:
    Timestampable
  columns:
    id:
      type: string(36)
      primary: true
    titre: string(256)
    titre_complet: string(512)
    section_id: string(36)
    min_date: string(15)
    timestamp: integer
    nb_interventions: integer
  relations:
    Section:
      foreignAlias: SubSections

Intervention:
  actAs: 
    Timestampable: ~
    Taggable: ~
  columns:
#    id:
#      type: string(36)
#      primary: true
    nb_mots: integer
    md5: 
      type: string(36)
      unique: true
    intervention: 
      type: string
    timestamp: integer
    source: string(128)
    seance_id: integer
    section_id: string(36)
    type:
      type: enum
      values: ['commission', 'question', 'loi']
    date: date
    personnalite_id: integer
    parlementaire_id: integer
    fonction: string(512)
  relations:
    Section:
      foreignAlias: Interventions
    Seance:
      foreignAlias: Interventions
    Personnalite:
      class: Personnalite
      foreignAlias: Interventions
    Parlementaire:
      class: Parlementaire
      foreignAlias: Interventions
  indexes:
    ft_intervention:
      fields: [intervention]
      type: fulltext

Amendement:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
    source:
      type: string(255)
      unique: true
    legislature: integer
    texteloi_id: integer
    numero: integer
    rectif: integer
    sujet: string(100)
    sort:
      type: enum
      values: ['Indéfini', 'Adopté', 'Irrecevable', 'Rejeté', 'Retiré', 'Tombe', 'Non soutenu', 'Retiré avant séance']
    date: date
    signataires: string
    texte: 
      type: string
    expose: 
      type: string
    content_md5: string(36)
  relations:
    Parlementaires:
      class: Parlementaire
      refClass: ParlementaireAmendement
      foreignAlias: Amendements
  indexes:
    ft_amendements:
      fields: [sujet, texte, expose]
      type: fulltext

ParlementaireAmendement:
  actAs:
    Timestampable:
  columns:
    parlementaire_id: integer
    amendement_id: string(36)
  relations:
    Parlementaire:
      foreignAlias: ParlementaireAmendements
    Amendement:
      foreignAlias: ParlementaireAmendements

Utilisateur:
  actAs:
    Timestampable:
    Sluggable:
      fields: [login]
  columns:
    login:
      type: string(255)
      unique: true
    pass:
      type: string(40)
      notnull: true
    sexe: 
      type: enum
      values: ['H', 'F']
    naissance: date
    profession: string(255)
    parlementaire_id: integer
    mail: 
      type: string(255)
      notnull: true
    activation_id: string(32)
    activation:
      type: boolean
      default: 0
      notnull: true
    circo: string(255)
    circo_num: integer
    photo:
      type: boolean
      default: 0

VariableGlobale:
  actAs:
    Timestampable:
  columns:
    champ: string(32)
    value: blob