Personnalite:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: string(255)
    nom_de_famille: string(255)
    sexe: 
      type: enum
      values: ['H', 'F']
Parlementaire:
  columns:     
    nom_circo: string(255)
    num_circo: integer
    site_web: string(255)
    debut_mandat: date
    place_hemicycle:	integer
    url_an:	string(255)
    profession:	string(255)
    id_an:
      type:	integer
      unique:	true
    type:
      type:	enum
      values:	['depute', 'senateur']
  inheritance:
    extends: Personnalite
    type: concrete
  relations:
    Organismes:
      class: Organisme
      refClass: ParlementaireOrganisme
      foreignAlias: Parlementaires

Organisme:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: 
      type: string(255)
      unique: true
    type:
      type: enum
      values: ['parlementaire', 'groupe', 'extra']

ParlementaireOrganisme:
  columns:
    fonction: string(255)
    importance: integer
    debut_fonction: date
    organisme_id:
      type: integer
      primary: true
    parlementaire_id:
      type: integer
      primary: true
  relations:
    Parlementaire:
      foreignAlias: ParlementaireOrganismes
    Organisme:
      foreignAlias: ParlementaireOrganismes

Seance:
  actAs:
    Timestampable:
  columns:
    date: date
    numero_semaine: integer
    annee: integer
    type:
      type: enum
      values: ['commission', 'hemicycle']
    moment: string(30)
    organisme_id: integer
  relations:
    Organisme:
      foreignAlias: Seances
  indexes:
    uniq_index:
      fields: [organisme_id, date, moment]
      type: unique

Presence:
  actAs:
    Timestampable:
  columns:
    parlementaire_id: integer
    seance_id: integer
  relations:
    Parlementaire:
      foreignAlias: Presences
    Seance:
      foreignAlias: Presences

PreuvePresence:
  actAs:
    Timestampable:
  columns:
    presence_id: integer
    type:
      type: enum
      values: ['jo', 'intervention']
    source: string(50)
  relations:
    Presence:
      foreignAlias: Preuves

Intervention:
  actAs:
    Timestampable:
  columns:
    id:
      type: string(36)
      primary: true
    intervention: 
      type: blob
    timestamp: integer
    source: string(128)
    seance_id: integer
  relations:
    Seance:
      foreignAlias: Interventions
    Personnalites:
      class: Personnalite
      refClass: PersonnaliteIntervention
      foreignAlias: Interventions
    Parlementaires:
      class: Parlementaire
      refClass: PersonnaliteIntervention
      foreignAlias: Interventions

PersonnaliteIntervention:
  actAs:
    Timestampable:
  columns:
    personnalite_id: integer
    parlementaire_id: integer
    intervention_id: string(36)
  relations:
    Personnalite:
      foreignAlias: PersonnaliteInterventions
    Parlementaire:
      foreignAlias: PersonnaliteInterventions
    Intervention:
      foreignAlias: PersonnaliteInterventions
