options:
    type: MyISAM
    collate: latin1_swedish_ci
    charset: latin1

Personnalite:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: string(255)
    nom_de_famille: string(255)
    sexe: 
      type: enum
      values: ['H', 'F']

Parlementaire:
  columns:     
    nom_circo: string(255)
    num_circo: integer
    site_web: string(255)
    debut_mandat: date
    fin_mandat: date
    place_hemicycle: integer
    url_an: string(255)
    profession: string(255)
    photo: blob
    id_an:
      type: integer
      unique: true
    type:
      type: enum
      values: ['depute', 'senateur']
    groupe_acronyme: string(8)
    adresses: string
    autres_mandats: string
    mails: string
    top: string
  inheritance:
    extends: Personnalite
    type: concrete
  relations:
    Organismes:
      class: Organisme
      refClass: ParlementaireOrganisme
      foreignAlias: Parlementaires
  indexes:
    uniq_url:
      fields: [url_an]
      type: unique

Organisme:
  actAs:
    Timestampable:
    Sluggable:
      fields: [nom]
      unique: true
  columns:
    nom: 
      type: string(255)
      unique: true
#      notnull: true
    type:
      type: enum
      values: ['parlementaire', 'groupe', 'extra']

ParlementaireOrganisme:
  columns:
    fonction: string(512)
    importance: integer
    debut_fonction: date
    organisme_id:
      type: integer
      primary: true
    parlementaire_id:
      type: integer
      primary: true
  relations:
    Parlementaire:
      foreignAlias: ParlementaireOrganismes
    Organisme:
      foreignAlias: ParlementaireOrganismes

Seance:
  actAs:
    Timestampable:
  columns:
    date: date
    numero_semaine: integer
    annee: integer
    type:
      type: enum
      values: ['commission', 'hemicycle']
    moment: string(30)
    organisme_id: integer
    tagged: boolean
    session: string(10)
  relations:
    Organisme:
      foreignAlias: Seances
  indexes:
    uniq_index:
      fields: [organisme_id, date, moment]
      type: unique
    index_session:
      fields: [session]
    index_semaine:
      fields: [annee, numero_semaine]
    index_annee:
      fields: [annee]

Presence:
  actAs:
    Timestampable:
  columns:
    parlementaire_id: integer
    seance_id: integer
    nb_preuves: integer
    date: date
  relations:
    Parlementaire:
      foreignAlias: Presences
    Seance:
      foreignAlias: Presences

PreuvePresence:
  actAs:
    Timestampable:
  columns:
    presence_id: integer
    type:
      type: enum
      values: ['jo', 'intervention']
    source: string(200)
  relations:
    Presence:
      foreignAlias: Preuves

Section:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
    md5:
      type: string(36)
      unique: true
    titre: string(256)
    titre_complet: string(512)
    section_id: integer
    min_date: string(15)
    timestamp: integer
    nb_interventions: integer
  relations:
    Section:
      foreignAlias: SubSections

Intervention:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
#    id:
#      type: string(36)
#      primary: true
    nb_mots: integer
    md5: 
      type: string(36)
      unique: true
    intervention: 
      type: string
    timestamp: integer
    source: string(128)
    seance_id: integer
    section_id: integer
    type:
      type: enum
      values: ['commission', 'question', 'loi']
    date: date
    personnalite_id: integer
    parlementaire_id: integer
    fonction: string(512)
  relations:
    Section:
      foreignAlias: Interventions
    Seance:
      foreignAlias: Interventions
    Personnalite:
      class: Personnalite
      foreignAlias: Interventions
    Parlementaire:
      class: Parlementaire
      foreignAlias: Interventions
  inheritance:
    extends: ObjectCommentable
    type: concrete
  indexes:
    date_intervention:
      fields: [date]
    ft_intervention:
      fields: [intervention]
      type: fulltext

Amendement:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
    source:
      type: string(255)
      unique: true
    legislature: integer
    texteloi_id: integer
    numero: integer
    rectif: integer
    sujet: string(100)
    sort:
      type: enum
      values: ['Indéfini', 'Adopté', 'Irrecevable', 'Rejeté', 'Retiré', 'Tombe', 'Non soutenu', 'Retiré avant séance']
    date: date
    signataires: string
    texte: 
      type: string
    expose: 
      type: string
    content_md5: string(36)
  relations:
    Parlementaires:
      class: Parlementaire
      refClass: ParlementaireAmendement
      foreignAlias: Amendements
  inheritance:
    extends: ObjectCommentable
    type: concrete
  indexes:
    ft_amendements:
      fields: [sujet, texte, expose]
      type: fulltext

QuestionEcrite:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
    source:
      type: string(255)
      unique: true
    legislature: integer
    numero: integer
    date: date
    ministere: string
    themes: string
    question:
      type: string
    reponse:
      type: string
    content_md5: string(36)
    parlementaire_id: integer
  inheritance:
    extends: ObjectCommentable
    type: concrete
  relations:
    Parlementaire:
      class: Parlementaire
      foreignAlias: QuestionEcrites

ParlementaireAmendement:
  actAs:
    Timestampable:
  columns:
    parlementaire_id: integer
    amendement_id: string(36)
    numero_signataire: integer
  relations:
    Parlementaire:
      foreignAlias: ParlementaireAmendements
    Amendement:
      foreignAlias: ParlementaireAmendements

Citoyen:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [login]
      unique: true
  columns:
    login:
      type: string(128)
      unique: true
    password:
      type: string(40)
    email:
      type: string(255)
      unique: true
      notnull: true
    activite: string(255)
    url_site: string(255)
    employe_an:
      type: boolean
      default: 0
    travail_pour: integer
    naissance: date
    sexe: 
      type: enum
      values: [null, 'H', 'F']
    nom_circo: string(255)
    num_circo: integer
    photo: blob
    activation_id: string(32)
    is_active:
      type: boolean
      default: 0
    role: 
      type: enum
      values: ['membre', 'moderateur', 'admin']
      default: membre
    last_login: timestamp
  indexes:
    is_active:
      fields: [is_active]
    role:
      fields: [role]

VariableGlobale:
  actAs:
    Timestampable:
  columns:
    champ: string(32)
    value: blob

Commentaire:
  actAs:
    Timestampable:
  columns:
    citoyen_id: integer
    commentaire: string
    is_public: boolean
    ip_address: string(512)
    rate: integer
    object_type: string(64)
    object_id: integer
    lien: string(128)
    presentation: string(512)
  relations:
    Citoyen:
      foreignAlias: Commentaires
    Parlementaires:
      class: Parlementaire
      refClass: CommentaireParlementaires
      foreignAlias: Commentaires
  inheritance:
    extends: ObjectRated
    type: concrete
  indexes:
    commentable:
      fields: [object_type, object_id]

CommentaireParlementaires:
 columns:
   parlementaire_id: integer
   commentaire_id: integer
 relations:
   Parlementaire:
   Commentaire:
 indexes:
   unique:
     fields: [parlementaire_id, commentaire_id]
     type: unique

ObjectRated:
  columns:
    rate: integer

ObjectCommentable:
  columns:
    nb_commentaires: integer

Rate:
  actAs:
    Timestampable:
  columns:
    object_type: string(50)
    object_id: integer
    rate: integer
    citoyen_id: integer
  relations:
    Citoyen:
      foreignAlias: Rates
    Object:
      foreignAlias: Rates
  indexes:
    unique:
      fields: [object_type, object_id, citoyen_id]
      type: unique

Article:
  actAs:
    Timestampable:
    Versionable:
    Sluggable:
      fields: [titre]
  columns:
    titre: string(254)
    corps: string
    user_corps: string
    categorie: string(128)
    citoyen_id: integer
    article_id: integer
    link: string(255)
    status:
      type: enum
      values: ['public', 'brouillon', 'offline']
      default: 'brouillon'
    object_id: integer
  inheritance:
    extends: ObjectRated
    type: concrete
  inheritance:
    extends: ObjectCommentable
    type: concrete
  relations:
    Citoyen:
      foreignAlias: Articles
    Article:
      foreignAlias: SousArticles
  indexes:
    icategories:
      fields: [categorie]
    iobject:
      fields: [categorie, object_id]
      unique: true
    ititre:
      fields: [categorie, titre]
    ititrecitoyen:
      fields: [categorie, titre, citoyen_id]
    iarticle:
      fields: [article_id]
